import { useState } from 'react'
import { importPrivateGitHubMilestone, importPublicGitHubMilestone, listPrivateGitHubMilestones, listPublicGitHubMilestones, Membership, PublicGitHubMilestone } from './adx-api-client'

export function ImportGitHubMilestoneModal({ workspace, onClose, onDone }: { workspace?: Membership; onClose: () => void; onDone: () => void }) {
  const [repositoryAccess, setRepositoryAccess] = useState<'public' | 'private'>('public'); const [owner, setOwner] = useState(''); const [repository, setRepository] = useState(''); const [milestones, setMilestones] = useState<PublicGitHubMilestone[]>([]); const [milestone, setMilestone] = useState(''); const [featureOwner, setFeatureOwner] = useState('Product Operations'); const [targetRepository, setTargetRepository] = useState(''); const [riskTier, setRiskTier] = useState('R2'); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(false)
  const lookup = async () => {
    if (!workspace || !owner.trim() || !repository.trim()) return
    setLoading(true); setMessage(`Loading ${repositoryAccess} GitHub milestones…`); setMilestones([]); setMilestone('')
    try { const response = repositoryAccess === 'private' ? await listPrivateGitHubMilestones(workspace.workspaceId, owner.trim(), repository.trim()) : await listPublicGitHubMilestones(workspace.workspaceId, owner.trim(), repository.trim()); setMilestones(response.milestones); setMessage(response.milestones.length ? 'Choose a milestone. Each retained GitHub issue will become an ADX feature.' : `This ${repositoryAccess} repository has no open milestones.`) } catch (error) { setMessage(describeMilestoneImportError(error, workspace, repositoryAccess, 'lookup')) } finally { setLoading(false) }
  }
  const importMilestone = async () => {
    if (!workspace || !milestone || !featureOwner.trim() || !targetRepository.trim()) return
    setLoading(true); setMessage('Retaining the milestone context and creating one feature per GitHub issue…')
    try { const input = { owner: owner.trim(), repository: repository.trim(), milestone: Number(milestone), featureOwner: featureOwner.trim(), targetRepository: targetRepository.trim(), riskTier }; const response = repositoryAccess === 'private' ? await importPrivateGitHubMilestone(workspace.workspaceId, input) : await importPublicGitHubMilestone(workspace.workspaceId, input); const imported = response.results.filter((result) => result.status === 'IMPORTED').length; const clarification = response.results.filter((result) => result.status === 'REQUIRES_CLARIFICATION').length; const failed = response.results.length - imported - clarification; setMessage(`Created ${imported} feature${imported === 1 ? '' : 's'}${clarification ? `; ${clarification} need${clarification === 1 ? 's' : ''} clarification` : ''}${failed ? `; ${failed} failed` : ''}.`); if (imported || clarification) onDone() } catch (error) { setMessage(describeMilestoneImportError(error, workspace, repositoryAccess, 'import')) } finally { setLoading(false) }
  }
  return <div className="adx-modal-backdrop"><section className="adx-modal adx-import"><div><p className="adx-eyebrow">GITHUB MILESTONE</p><h2>Import milestone issues as features</h2><p>Each non-pull-request issue becomes an ADX feature, with its milestone retained as shared context. ADX never accepts a GitHub credential in this browser.</p></div><div><label>Repository access<select value={repositoryAccess} onChange={(event) => { setRepositoryAccess(event.target.value as 'public' | 'private'); setMilestones([]); setMilestone(''); setMessage('') }}><option value="public">Public repository</option><option value="private">Private repository</option></select></label>{repositoryAccess === 'private' && <p>A server administrator must configure ADX's read-only GitHub access before private repositories can be read.</p>}<label>GitHub owner<input value={owner} onChange={(event) => setOwner(event.target.value)} placeholder="e.g. ravikumarraman-cell" autoComplete="off" /></label><label>Repository<input value={repository} onChange={(event) => setRepository(event.target.value)} placeholder="e.g. health-x" autoComplete="off" /></label><button className="adx-secondary" disabled={loading || !owner.trim() || !repository.trim()} onClick={lookup}>Find open milestones</button></div>{milestones.length > 0 && <><label>Milestone<select value={milestone} onChange={(event) => setMilestone(event.target.value)}><option value="">Choose a milestone</option>{milestones.map((item) => <option key={item.number} value={item.number}>#{item.number} · {item.title} ({item.openIssues} open issues)</option>)}</select></label><label>ADX feature owner<input value={featureOwner} onChange={(event) => setFeatureOwner(event.target.value)} /></label><label>Target repository<input value={targetRepository} onChange={(event) => setTargetRepository(event.target.value)} placeholder="e.g. health-x" /></label><label>Initial risk tier<select value={riskTier} onChange={(event) => setRiskTier(event.target.value)}>{['R0', 'R1', 'R2', 'R3', 'R4'].map((value) => <option key={value}>{value}</option>)}</select></label></>}{message && <p>{message}</p>}<div><button className="adx-secondary" disabled={loading} onClick={onClose}>Cancel</button><button className="adx-primary" disabled={loading || !milestone || !featureOwner.trim() || !targetRepository.trim()} onClick={importMilestone}>Import milestone issues</button></div></section></div>
}

function describeMilestoneImportError(error: unknown, workspace: Membership | undefined, repositoryAccess: 'public' | 'private', phase: 'lookup' | 'import') {
  const fallback = phase === 'lookup' ? 'GitHub milestones could not be loaded.' : 'The milestone could not be imported.'
  if (!(error instanceof Error)) return fallback
  const code = (error as { code?: string }).code
  if (code !== 'CAPABILITY_MISSING') return error.message || fallback
  const roles = workspace?.roles?.length ? workspace.roles.join(', ') : 'unknown'
  const requiredCapability = phase === 'import' ? 'workspace.manage' : 'workspace.read'
  return `Your current workspace role (${roles}) does not include ${requiredCapability}, which is required to ${phase === 'lookup' ? 'load' : 'import'} ${repositoryAccess} GitHub milestones. If you were recently granted a new role, sign out and back in to refresh your session.`
}
