import { test, expect } from '@playwright/test'
import { randomUUID } from 'node:crypto'

const workspace = 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'
const design = { architectureDecision: { decision: 'Use a tenant-scoped boundary.' }, interfaceDelta: { changes: ['POST /design'] }, migrationPlan: { steps: ['apply migration'] }, threatModel: { threats: [{ id: 'T1', mitigation: 'authorize', residualRisk: 'low' }] }, dependencies: { items: [{ name: 'pg', license: 'MIT' }] }, testStrategy: { layers: ['unit', 'integration', 'browser'] } }

test('design review deep link explains retained artifacts, residual risk, and the safe next action', async ({ page, request }) => {
  const changeCaseTitle = `Design review deep link ${randomUUID()}`
  const token = async (as) => (await (await request.get(`/__test/session?as=${as}`)).json()).token
  const alice = await token('alice'); const approver = await token('approver'); const reviewer = await token('designReviewer')
  const headers = (value) => ({ authorization: `Bearer ${value}`, 'content-type': 'application/json', 'idempotency-key': `stage4-ui-${randomUUID()}` })
  const created = await request.post(`/v1/workspaces/${workspace}/change-cases`, { headers: headers(alice), data: { title: changeCaseTitle, riskTier: 'R2' } }); const { changeCaseId, projectionVersion: createVersion } = await created.json()
  const intake = await request.post(`/v1/workspaces/${workspace}/change-cases/${changeCaseId}/transitions`, { headers: headers(alice), data: { toState: 'INTAKE', expectedVersion: createVersion } }); let { projectionVersion: version } = await intake.json()
  const captured = await request.post(`/v1/workspaces/${workspace}/change-cases/${changeCaseId}/intake`, { headers: headers(alice), data: { expectedVersion: version, intent: { outcome: 'Review a retained design package', owner: 'Security', acceptanceCriteria: 'A reviewer can see all design artifacts, residual risk, and the next safe action.', targetRepository: 'adx-api', assets: [], sourceContent: 'Stage 4 browser evidence', sourceName: 'stage4.md' } } }); ({ projectionVersion: version } = await captured.json())
  const classified = await request.post(`/v1/workspaces/${workspace}/change-cases/${changeCaseId}/classify`, { headers: headers(alice), data: { expectedVersion: version } }); ({ projectionVersion: version } = await classified.json())
  const stories = await request.post(`/v1/workspaces/${workspace}/change-cases/${changeCaseId}/stories`, { headers: headers(alice), data: { expectedVersion: version, stories: [{ title: 'Review design', narrative: 'As a reviewer, I need a retained design package.', scenarios: [{ given: 'a classified Change Case', when: 'I open design review', then: 'I see the security decision context' }] }] } }); const story = await stories.json(); version = story.projectionVersion
  const storyApproval = await request.post(`/v1/workspaces/${workspace}/change-cases/${changeCaseId}/story-decision`, { headers: headers(approver), data: { expectedVersion: version, storyDigest: story.storyDigest, decision: 'APPROVED', rationale: 'Story contract is sufficient.' } }); ({ projectionVersion: version } = await storyApproval.json())
  await page.context().addCookies([{ name: 'adx_session', value: alice, url: 'http://127.0.0.1:3111' }]); await page.goto(`/v1/workspaces/${workspace}/change-cases/${changeCaseId}/design-review`)
  await expect(page.getByRole('link', { name: 'Capture design package' })).toBeVisible(); await page.getByRole('link', { name: 'Capture design package' }).click()
  await page.getByLabel('Architecture decision').fill(design.architectureDecision.decision); await page.getByLabel('Interface or schema changes').fill(design.interfaceDelta.changes.join('\n')); await page.getByLabel('Migration plan').fill(design.migrationPlan.steps.join('\n')); await page.getByLabel('Primary threat').fill(design.threatModel.threats[0].id); await page.getByLabel('Mitigation').fill(design.threatModel.threats[0].mitigation); await page.getByLabel('Residual risk').fill(design.threatModel.threats[0].residualRisk); await page.getByLabel('Dependencies and licenses').fill('pg | MIT'); await page.getByRole('checkbox', { name: 'Unit' }).check(); await page.getByRole('button', { name: 'Capture design package for review' }).click(); await page.waitForURL(/\/design-review$/)
  const designViewResponse = await request.get(`/v1/workspaces/${workspace}/change-cases/${changeCaseId}/design`, { headers: headers(alice) }); const designView = await designViewResponse.json(); version = designView.changeCase?.projectionVersion ?? version
  await page.context().addCookies([{ name: 'adx_session', value: reviewer, url: 'http://127.0.0.1:3111' }]); await page.goto(`/v1/workspaces/${workspace}/change-cases/${changeCaseId}/design-review`)
  await expect(page.getByRole('heading', { name: changeCaseTitle })).toBeVisible(); await expect(page.getByText('Review the package, residual risk, and verification plan before advancing the work.')).toBeVisible(); await expect(page.getByText('Threat model and residual risk')).toBeVisible(); await expect(page.locator('.digest')).toHaveText(designView.design.designDigest); await expect(page.getByText('Evidence at a glance')).toBeVisible(); await expect(page.getByText('Inspect retained evidence')).toHaveCount(4); await page.getByRole('radio', { name: 'Approve design' }).check(); await page.getByLabel('Review rationale').fill('The package addresses the recorded threat and has an executable verification strategy.'); await page.getByRole('button', { name: 'Record design decision' }).click(); await expect(page.getByText('Design approved. Reloading review…')).toBeVisible(); await page.reload(); await expect(page.getByText('Design approved')).toBeVisible()
  const currentCase = await request.get(`/v1/workspaces/${workspace}/change-cases/${changeCaseId}`, { headers: headers(alice) })
  const { changeCase } = await currentCase.json()
  const cancelled = await request.post(`/v1/workspaces/${workspace}/change-cases/${changeCaseId}/transitions`, { headers: headers(alice), data: { toState: 'CANCELLED', expectedVersion: changeCase.projectionVersion } })
  await expect(cancelled).toBeOK()
})
