import { test, expect } from '@playwright/test'
import { randomUUID } from 'node:crypto'
const workspace = 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'
test('story review deep link presents authoritative retained intent, risk, and BDD stories', async ({ page, request }) => {
  const session = await request.get('/__test/session?as=alice'); const { token } = await session.json(); const headers = (key) => ({ authorization: `Bearer ${token}`, 'content-type': 'application/json', 'idempotency-key': key })
  const created = await request.post(`/v1/workspaces/${workspace}/change-cases`, { headers: headers(`stage3-ui-create-${randomUUID()}`), data: { title: 'Story review deep link', riskTier: 'R1' } }); const { changeCaseId, projectionVersion: createdVersion } = await created.json()
  const moved = await request.post(`/v1/workspaces/${workspace}/change-cases/${changeCaseId}/transitions`, { headers: headers(`stage3-ui-intake-${randomUUID()}`), data: { toState: 'INTAKE', expectedVersion: createdVersion } }); const { projectionVersion: intakeVersion } = await moved.json()
  const captured = await request.post(`/v1/workspaces/${workspace}/change-cases/${changeCaseId}/intake`, { headers: headers(`stage3-ui-capture-${randomUUID()}`), data: { expectedVersion: intakeVersion, intent: { outcome: 'Review a governed story', owner: 'Product Operations', acceptanceCriteria: 'A reviewer can understand risk and acceptance scenarios without raw transcripts.', targetRepository: 'health-auth-service', assets: [{ name: 'clinical record', classification: 'restricted' }], sourceContent: 'UI story review source', sourceName: 'review.csv' } } }); const { projectionVersion: capturedVersion } = await captured.json()
  const classified = await request.post(`/v1/workspaces/${workspace}/change-cases/${changeCaseId}/classify`, { headers: headers(`stage3-ui-classify-${randomUUID()}`), data: { expectedVersion: capturedVersion } }); const { projectionVersion: classifiedVersion } = await classified.json()
  await request.post(`/v1/workspaces/${workspace}/change-cases/${changeCaseId}/stories`, { headers: headers(`stage3-ui-story-${randomUUID()}`), data: { expectedVersion: classifiedVersion, stories: [{ key: 'STORY-UI', title: 'Review intake', narrative: 'As a reviewer, I need a readable contract.', scenarios: [{ given: 'a retained source', when: 'I open review', then: 'I see BDD acceptance criteria' }] }] } })
  await page.context().addCookies([{ name: 'adx_session', value: token, url: 'http://127.0.0.1:3109' }]); await page.goto(`/v1/workspaces/${workspace}/change-cases/${changeCaseId}/story-review`)
  await expect(page.getByRole('heading', { name: 'Story review deep link' })).toBeVisible(); await expect(page.getByText('R4 effective risk')).toBeVisible(); await expect(page.getByText('Given')).toBeVisible(); await expect(page.getByText('ONE SAFE NEXT ACTION')).toBeVisible(); await page.reload(); await expect(page.getByText('review.csv')).toBeVisible()
})
