import { test, expect } from '@playwright/test'
import { randomUUID } from 'node:crypto'
const workspace = 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'
test('story review deep link presents authoritative retained intent, risk, and BDD stories', async ({ page, request }) => {
  const pageErrors = []; page.on('pageerror', (error) => pageErrors.push(error.message))
  const session = await request.get('/__test/session?as=alice'); const { token } = await session.json(); const headers = (key) => ({ authorization: `Bearer ${token}`, 'content-type': 'application/json', 'idempotency-key': key })
  const created = await request.post(`/v1/workspaces/${workspace}/change-cases`, { headers: headers(`stage3-ui-create-${randomUUID()}`), data: { title: 'Story review deep link', riskTier: 'R1' } }); const { changeCaseId, projectionVersion: createdVersion } = await created.json()
  const moved = await request.post(`/v1/workspaces/${workspace}/change-cases/${changeCaseId}/transitions`, { headers: headers(`stage3-ui-intake-${randomUUID()}`), data: { toState: 'INTAKE', expectedVersion: createdVersion } }); const { projectionVersion: intakeVersion } = await moved.json()
  const captured = await request.post(`/v1/workspaces/${workspace}/change-cases/${changeCaseId}/intake`, { headers: headers(`stage3-ui-capture-${randomUUID()}`), data: { expectedVersion: intakeVersion, intent: { outcome: 'Review a governed story', owner: 'Product Operations', acceptanceCriteria: 'A reviewer can understand risk and acceptance scenarios without raw transcripts.', targetRepository: 'health-auth-service', assets: [{ name: 'clinical record', classification: 'restricted' }], sourceContent: 'UI story review source', sourceName: 'review.csv' } } }); const { projectionVersion: capturedVersion } = await captured.json()
  const classified = await request.post(`/v1/workspaces/${workspace}/change-cases/${changeCaseId}/classify`, { headers: headers(`stage3-ui-classify-${randomUUID()}`), data: { expectedVersion: capturedVersion } }); const { projectionVersion: classifiedVersion } = await classified.json()
  await page.context().addCookies([{ name: 'adx_session', value: token, url: 'http://127.0.0.1:3109' }]); await page.goto(`/v1/workspaces/${workspace}/change-cases/${changeCaseId}/story-workshop`)
  expect(pageErrors).toEqual([])
  await expect(page.locator('.signed-in-indicator')).toHaveAttribute('aria-label', 'Signed in as alice')
  await expect(page.getByRole('link', { name: '← Back to ADX home' })).toHaveAttribute('href', 'http://127.0.0.1:4173/')
  await expect(page.locator('.story-card')).toHaveCount(1)
  await page.route('**/story-suggestions', async (route) => route.fulfill({ contentType: 'application/json', body: JSON.stringify({ suggestions: [{ title: 'View authorization status', narrative: 'As a member, I want to view my authorization status, so that I know what happens next.', scenarios: [{ given: 'a submitted authorization', when: 'the member opens its status', then: 'the current status and next action are shown' }] }] }) }))
  await page.getByRole('button', { name: 'Generate AI suggestions' }).click()
  await page.getByRole('checkbox').check()
  await page.getByRole('button', { name: 'Accept selected suggestions' }).click()
  expect(pageErrors).toEqual([])
  await expect(page.locator('.story-card')).toHaveCount(1)
  await expect(page.locator('.story-card input[name="title"]')).toHaveValue('View authorization status')
  await expect(page.locator('.story-card label').first()).toHaveCSS('color', 'rgb(22, 59, 85)')
  await expect(page.locator('.story-card input').first()).toHaveCSS('border-top-width', '2px')
  let submitted
  await page.route('**/stories', async (route) => { submitted = JSON.parse(route.request().postData() ?? '{}'); await route.fulfill({ contentType: 'application/json', body: '{}' }) })
  await page.getByRole('button', { name: 'Submit stories for independent review' }).click()
  await expect(page.locator('#workshop-status')).toHaveText('Stories submitted. Opening independent review…')
  expect(submitted.stories).toHaveLength(1)
  expect(submitted.stories[0].title).toBe('View authorization status')
  await request.post(`/v1/workspaces/${workspace}/change-cases/${changeCaseId}/stories`, { headers: headers(`stage3-ui-story-${randomUUID()}`), data: { expectedVersion: classifiedVersion, stories: submitted.stories } })
  await page.goto(`/v1/workspaces/${workspace}/change-cases/${changeCaseId}/story-review`)
  await expect(page.locator('.signed-in-indicator')).toHaveAttribute('aria-label', 'Signed in as alice')
  await expect(page.getByRole('link', { name: 'Return to workspace' })).toHaveAttribute('href', 'http://127.0.0.1:4173/?mode=real')
  await expect(page.getByRole('heading', { name: 'Story review deep link' })).toBeVisible(); await expect(page.getByText('R4 effective risk')).toBeVisible(); await expect(page.getByText('Given')).toBeVisible(); await expect(page.getByText('ONE SAFE NEXT ACTION')).toBeVisible(); await page.reload(); await expect(page.getByText('review.csv')).toBeVisible()
})
