export type ImportedFeature = { featureId: string; title: string; description: string; priority: string; owner: string; targetRepository: string; acceptanceCriteria: string; riskTier: string; sourceUrl: string; dependencies: string; nonFunctionalRequirements: string; raw: string }
export type ImportRow = { row: number; feature?: ImportedFeature; errors: string[] }
const required = ['feature_id', 'title', 'description', 'priority', 'owner', 'target_repository', 'acceptance_criteria', 'risk_tier']

export function parseFeatureCsv(text: string): ImportRow[] {
  const rows = csvRows(text); if (rows.length < 2) return [{ row: 1, errors: ['The file needs a header and at least one feature row.'] }]
  const headers = rows[0].map((value) => value.trim().toLowerCase()); const missing = required.filter((name) => !headers.includes(name)); if (missing.length) return [{ row: 1, errors: [`Missing required columns: ${missing.join(', ')}`] }]
  const at = (cells: string[], name: string) => cells[headers.indexOf(name)]?.trim() ?? ''; const seen = new Set<string>()
  return rows.slice(1).filter((cells) => cells.some((value) => value.trim())).map((cells, index) => { const feature: ImportedFeature = { featureId: at(cells,'feature_id'), title: at(cells,'title'), description: at(cells,'description'), priority: at(cells,'priority'), owner: at(cells,'owner'), targetRepository: at(cells,'target_repository'), acceptanceCriteria: at(cells,'acceptance_criteria'), riskTier: at(cells,'risk_tier'), sourceUrl: at(cells,'source_url'), dependencies: at(cells,'dependencies'), nonFunctionalRequirements: at(cells,'non_functional_requirements'), raw: JSON.stringify(Object.fromEntries(headers.map((header, cell) => [header, cells[cell] ?? '']))) }; const errors: string[] = []; if (!feature.featureId) errors.push('feature_id is required'); else if (seen.has(feature.featureId)) errors.push('feature_id is duplicated in this file'); else seen.add(feature.featureId); if (!feature.title) errors.push('title is required'); if (!feature.owner) errors.push('owner is required'); if (!feature.targetRepository) errors.push('target_repository is required'); if (feature.acceptanceCriteria.length < 12) errors.push('acceptance_criteria must describe an observable outcome'); if (!['P0','P1','P2'].includes(feature.priority)) errors.push('priority must be P0, P1, or P2'); if (!['R0','R1','R2','R3','R4'].includes(feature.riskTier)) errors.push('risk_tier must be R0–R4'); return { row: index + 2, feature, errors } })
}
function csvRows(text: string) { const rows: string[][] = [[]]; let value = ''; let quoted = false; for (let i=0;i<text.length;i+=1) { const char=text[i]; if (char==='"') { if (quoted && text[i+1]==='"') { value+='"'; i+=1 } else quoted=!quoted } else if (char===',' && !quoted) { rows.at(-1)!.push(value); value='' } else if ((char==='\n' || char==='\r') && !quoted) { if (char==='\r' && text[i+1]==='\n') i+=1; rows.at(-1)!.push(value); value=''; rows.push([]) } else value+=char } rows.at(-1)!.push(value); return rows }
