import { useState } from 'react'
import { importPublicGitHubMilestone, listPublicGitHubMilestones, Membership, PublicGitHubMilestone } from './adx-api-client'

export function ImportGitHubMilestoneModal({ workspace, onClose, onDone }: { workspace?: Membership; onClose: () => void; onDone: () => void }) {
  const [owner, setOwner] = useState(''); const [repository, setRepository] = useState(''); const [milestones, setMilestones] = useState<PublicGitHubMilestone[]>([]); const [milestone, setMilestone] = useState(''); const [featureOwner, setFeatureOwner] = useState('Product Operations'); const [targetRepository, setTargetRepository] = useState(''); const [riskTier, setRiskTier] = useState('R2'); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(false)
  const lookup = async () => {
    if (!workspace || !owner.trim() || !repository.trim()) return
    setLoading(true); setMessage('Loading public GitHub milestones…'); setMilestones([]); setMilestone('')
    try { const response = await listPublicGitHubMilestones(workspace.workspaceId, owner.trim(), repository.trim()); setMilestones(response.milestones); setMessage(response.milestones.length ? 'Choose a milestone. Each retained GitHub issue will become an ADX feature.' : 'This public repository has no open milestones.') } catch (error) { setMessage(error instanceof Error ? error.message : 'GitHub milestones could not be loaded.') } finally { setLoading(false) }
  }
  const importMilestone = async () => {
    if (!workspace || !milestone || !featureOwner.trim() || !targetRepository.trim()) return
    setLoading(true); setMessage('Retaining the milestone context and creating one feature per GitHub issue…')
    try { const response = await importPublicGitHubMilestone(workspace.workspaceId, { owner: owner.trim(), repository: repository.trim(), milestone: Number(milestone), featureOwner: featureOwner.trim(), targetRepository: targetRepository.trim(), riskTier }); const imported = response.results.filter((result) => result.status === 'IMPORTED').length; const clarification = response.results.filter((result) => result.status === 'REQUIRES_CLARIFICATION').length; const failed = response.results.length - imported - clarification; setMessage(`Created ${imported} feature${imported === 1 ? '' : 's'}${clarification ? `; ${clarification} need${clarification === 1 ? 's' : ''} clarification` : ''}${failed ? `; ${failed} failed` : ''}.`); if (imported || clarification) onDone() } catch (error) { setMessage(error instanceof Error ? error.message : 'The milestone could not be imported.') } finally { setLoading(false) }
  }
  return <div className="adx-modal-backdrop"><section className="adx-modal adx-import"><div><p className="adx-eyebrow">PUBLIC GITHUB MILESTONE</p><h2>Import a milestone's issues as features</h2><p>ADX reads only public GitHub metadata and issues. Each non-pull-request issue becomes an ADX feature; the milestone is retained as shared context. No GitHub token is accepted in this browser or stored by ADX.</p></div><div><label>GitHub owner<input value={owner} onChange={(event) => setOwner(event.target.value)} placeholder="e.g. ravikumarraman-cell" autoComplete="off" /></label><label>Repository<input value={repository} onChange={(event) => setRepository(event.target.value)} placeholder="e.g. ad-studio" autoComplete="off" /></label><button className="adx-secondary" disabled={loading || !owner.trim() || !repository.trim()} onClick={lookup}>Find open milestones</button></div>{milestones.length > 0 && <><label>Milestone<select value={milestone} onChange={(event) => setMilestone(event.target.value)}><option value="">Choose a milestone</option>{milestones.map((item) => <option key={item.number} value={item.number}>#{item.number} · {item.title} ({item.openIssues} open issues)</option>)}</select></label><label>ADX feature owner<input value={featureOwner} onChange={(event) => setFeatureOwner(event.target.value)} /></label><label>Target repository<input value={targetRepository} onChange={(event) => setTargetRepository(event.target.value)} placeholder="e.g. health-auth-service" /></label><label>Initial risk tier<select value={riskTier} onChange={(event) => setRiskTier(event.target.value)}>{['R0', 'R1', 'R2', 'R3', 'R4'].map((value) => <option key={value}>{value}</option>)}</select></label></>}{message && <p>{message}</p>}<div><button className="adx-secondary" disabled={loading} onClick={onClose}>Cancel</button><button className="adx-primary" disabled={loading || !milestone || !featureOwner.trim() || !targetRepository.trim()} onClick={importMilestone}>Import milestone issues</button></div></section></div>
}