import { randomUUID } from 'node:crypto'
import { ChangeCaseError, sha256 } from './change-case-ledger.mjs'

/** Provider declarations are simulation-only until a later explicit deployment integration. */
export function createReleaseEnvironmentAdapter({ providerId, environmentId, allowedArtifactPrefixes = ['sha256:'] }) {
  if (!text(providerId) || !text(environmentId) || !Array.isArray(allowedArtifactPrefixes) || !allowedArtifactPrefixes.length) throw new ChangeCaseError('RELEASE_ENVIRONMENT_ADAPTER_INVALID', 'A provider, environment, and artifact policy are required.')
  return Object.freeze({ providerId: providerId.trim(), environmentId: environmentId.trim(), mode: 'SIMULATION_ONLY', capabilities: Object.freeze({ deploy: false, featureFlag: true, progressiveRollout: true, telemetryRead: true, pause: true, resume: true, rollback: true }), permitsArtifact(artifactDigest) { return allowedArtifactPrefixes.some((prefix) => artifactDigest.startsWith(prefix)) } })
}

export function createFeatureFlagAdapter({ providerId, flagKey }) {
  if (!text(providerId) || !text(flagKey)) throw new ChangeCaseError('RELEASE_FLAG_ADAPTER_INVALID', 'A feature-flag provider and flag key are required.')
  return Object.freeze({ providerId: providerId.trim(), flagKey: flagKey.trim(), mode: 'SIMULATION_ONLY', capabilities: Object.freeze({ setAudience: false, pause: true, resume: true }) })
}

export function createReleaseAnalysisContract({ contractId, version, maxErrorRate, maxP95LatencyMs, minimumSamples, maximumTelemetryAgeMs }) {
  if (!text(contractId) || !text(version) || !number(maxErrorRate, 0, 1) || !number(maxP95LatencyMs, 1) || !Number.isInteger(minimumSamples) || minimumSamples < 1 || !Number.isInteger(maximumTelemetryAgeMs) || maximumTelemetryAgeMs < 1) throw new ChangeCaseError('RELEASE_ANALYSIS_CONTRACT_INVALID', 'A versioned release analysis contract requires error, latency, sample, and telemetry-freshness thresholds.')
  return Object.freeze({ contractId: contractId.trim(), version: version.trim(), maxErrorRate, maxP95LatencyMs, minimumSamples, maximumTelemetryAgeMs, digest: sha256({ schema: 'adx-release-analysis-contract-v1', contractId: contractId.trim(), version: version.trim(), maxErrorRate, maxP95LatencyMs, minimumSamples, maximumTelemetryAgeMs }) })
}

export function createProgressiveRolloutPlan({ releaseCandidate, environment, featureFlag, analysisContract, stages }) {
  if (releaseCandidate?.mode !== 'CONTROL_PLANE_ONLY' || environment?.mode !== 'SIMULATION_ONLY' || featureFlag?.mode !== 'SIMULATION_ONLY' || !analysisContract?.digest || !Array.isArray(stages) || !stages.length || !stages.every((stage) => Number.isInteger(stage) && stage > 0 && stage <= 100) || stages.at(-1) !== 100 || stages.some((stage, index) => index && stage <= stages[index - 1]) || !environment.permitsArtifact(releaseCandidate.provenance.artifactDigest)) throw new ChangeCaseError('PROGRESSIVE_ROLLOUT_PLAN_INVALID', 'A candidate, simulation-only adapters, allowed artifact, versioned analysis contract, and ascending rollout stages are required.')
  return Object.freeze({ rolloutPlanId: randomUUID(), mode: 'SIMULATION_ONLY', releaseCandidateId: releaseCandidate.releaseCandidateId, provenanceDigest: releaseCandidate.provenanceDigest, environment: Object.freeze({ providerId: environment.providerId, environmentId: environment.environmentId }), featureFlag: Object.freeze({ providerId: featureFlag.providerId, flagKey: featureFlag.flagKey }), analysisContract, stages: Object.freeze([...stages]), planDigest: sha256({ schema: 'adx-progressive-rollout-plan-v1', releaseCandidateId: releaseCandidate.releaseCandidateId, provenanceDigest: releaseCandidate.provenanceDigest, environmentId: environment.environmentId, flagKey: featureFlag.flagKey, analysisContractDigest: analysisContract.digest, stages }) })
}

export function evaluateReleaseAnalysis({ rolloutPlan, observation, now = Date.now() }) {
  if (!rolloutPlan?.planDigest || !observation || !number(observation.errorRate, 0, 1) || !number(observation.p95LatencyMs, 0) || !Number.isInteger(observation.sampleCount) || observation.sampleCount < 0 || !Number.isFinite(observation.observedAt)) throw new ChangeCaseError('RELEASE_ANALYSIS_OBSERVATION_INVALID', 'Release analysis requires bounded metrics, a sample count, and an observation time.')
  const contract = rolloutPlan.analysisContract; const age = now - observation.observedAt
  const decision = age > contract.maximumTelemetryAgeMs || observation.sampleCount < contract.minimumSamples ? 'PAUSE' : observation.errorRate > contract.maxErrorRate ? 'ROLLBACK' : observation.p95LatencyMs > contract.maxP95LatencyMs ? 'ROLLBACK' : 'PASS'
  return Object.freeze({ decision, reason: decision === 'PAUSE' ? age > contract.maximumTelemetryAgeMs ? 'TELEMETRY_STALE' : 'INSUFFICIENT_SAMPLE' : decision === 'ROLLBACK' ? observation.errorRate > contract.maxErrorRate ? 'ERROR_RATE_REGRESSION' : 'LATENCY_REGRESSION' : 'WITHIN_CONTRACT', observationDigest: sha256({ schema: 'adx-release-metric-observation-v1', rolloutPlanDigest: rolloutPlan.planDigest, observation }), contractDigest: contract.digest })
}

export class ProgressiveRolloutRegistry {
  #runs = new Map()
  start(plan) { if (plan?.mode !== 'SIMULATION_ONLY') throw new ChangeCaseError('PROGRESSIVE_ROLLOUT_PLAN_INVALID', 'A simulation-only rollout plan is required.'); const existing = this.#runs.get(plan.planDigest); if (existing) return Object.freeze({ accepted: true, deduplicated: true, rollout: existing }); const rollout = Object.freeze({ rolloutId: randomUUID(), plan, status: 'ACTIVE', stageIndex: 0, audiencePercent: plan.stages[0], history: Object.freeze([]) }); this.#runs.set(plan.planDigest, rollout); return Object.freeze({ accepted: true, deduplicated: false, rollout }) }
  observe(rolloutId, analysis) { const rollout = this.#find(rolloutId); if (rollout.status !== 'ACTIVE') throw new ChangeCaseError('ROLLOUT_NOT_ACTIVE', 'Only an active rollout may receive an analysis observation.'); const state = analysis?.decision === 'PASS' ? (rollout.stageIndex + 1 === rollout.plan.stages.length ? { status: 'COMPLETED', stageIndex: rollout.stageIndex, audiencePercent: 100 } : { status: 'ACTIVE', stageIndex: rollout.stageIndex + 1, audiencePercent: rollout.plan.stages[rollout.stageIndex + 1] }) : analysis?.decision === 'ROLLBACK' ? { status: 'ROLLBACK_REQUIRED', stageIndex: rollout.stageIndex, audiencePercent: rollout.audiencePercent } : analysis?.decision === 'PAUSE' ? { status: 'PAUSED', stageIndex: rollout.stageIndex, audiencePercent: rollout.audiencePercent } : null
    if (!state) throw new ChangeCaseError('RELEASE_ANALYSIS_OBSERVATION_INVALID', 'A release analysis decision is required.'); return this.#replace(rollout, state, analysis) }
  pause(rolloutId, principal, rationale) { const rollout = this.#find(rolloutId); if (principal?.type !== 'human' || !text(rationale) || !['ACTIVE','ROLLBACK_REQUIRED'].includes(rollout.status)) throw new ChangeCaseError('ROLLOUT_PAUSE_INVALID', 'A human operator and rationale may pause an active or rollback-required rollout.'); return this.#replace(rollout, { status: 'PAUSED', stageIndex: rollout.stageIndex, audiencePercent: rollout.audiencePercent }, { decision: 'PAUSE', reason: 'OPERATOR_KILL_SWITCH', principalId: principal.id, rationale: rationale.trim() }) }
  resume(rolloutId, principal, rationale) { const rollout = this.#find(rolloutId); if (principal?.type !== 'human' || !text(rationale) || rollout.status !== 'PAUSED') throw new ChangeCaseError('ROLLOUT_RESUME_INVALID', 'A human operator and rationale may resume only a paused rollout.'); return this.#replace(rollout, { status: 'ACTIVE', stageIndex: rollout.stageIndex, audiencePercent: rollout.audiencePercent }, { decision: 'RESUME', reason: 'OPERATOR_RESUME', principalId: principal.id, rationale: rationale.trim() }) }
  rollback(rolloutId, principal, rollbackArtifactDigest, compatible) { const rollout = this.#find(rolloutId); if (principal?.type !== 'human' || !text(rollbackArtifactDigest) || compatible !== true || !['PAUSED','ROLLBACK_REQUIRED','ACTIVE'].includes(rollout.status)) throw new ChangeCaseError('ROLLOUT_ROLLBACK_INVALID', 'Rollback requires a human operator, compatible rollback artifact, and an active, paused, or rollback-required rollout.'); return this.#replace(rollout, { status: 'ROLLED_BACK', stageIndex: rollout.stageIndex, audiencePercent: 0 }, { decision: 'ROLLBACK', reason: 'COMPATIBLE_TARGET_CONFIRMED', principalId: principal.id, rollbackArtifactDigest }) }
  #find(rolloutId) { for (const rollout of this.#runs.values()) if (rollout.rolloutId === rolloutId) return rollout; throw new ChangeCaseError('ROLLOUT_NOT_FOUND', 'Rollout was not found.') }
  #replace(rollout, state, event) { const updated = Object.freeze({ ...rollout, ...state, history: Object.freeze([...rollout.history, Object.freeze(event)]) }); this.#runs.set(rollout.plan.planDigest, updated); return Object.freeze({ accepted: true, rollout: updated }) }
}
const text = (value) => typeof value === 'string' && value.trim()
const number = (value, min, max = Infinity) => Number.isFinite(value) && value >= min && value <= max
