import assert from 'node:assert/strict'
import { generateKeyPairSync } from 'node:crypto'
import { mkdtemp, mkdir, readFile, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { createEvidenceBundle, executeVerificationSandbox, provisionVerificationSandbox, validateEvidencePass } from '../apps/adx-api/verification-evidence.mjs'
import { baselineVerifierAdapters, createVerifierAdapter, verifierCategories } from '../apps/adx-api/verification-adapters.mjs'

const image = 'alpine:3.20@sha256:d9e853e87e55526f6b2917df91a2115c36dd7c696a35be12163d44e6e2a4b6bc'; const root = await mkdtemp(join(tmpdir(), 'adx-stage6-')); const signer = { keyId: 'stage6-evidence-test', ...generateKeyPairSync('ed25519') }
const adapter = { verifierId: 'digest-check', version: '1.0.0', timeoutMs: 10_000, maxOutputBytes: 1024, command: () => ['/bin/sh', '-c', 'sha256sum candidate.txt'] }
try {
  await mkdir(join(root, 'candidate')); await writeFile(join(root, 'candidate', 'candidate.txt'), 'candidate content\n')
  const candidate = join(root, 'candidate'); const original = await readFile(join(candidate, 'candidate.txt'), 'utf8'); const firstPlan = await provisionVerificationSandbox({ candidateRoot: candidate, image, adapter, config: { checks: ['sha256'] } }); const firstResult = await executeVerificationSandbox(firstPlan); assert.equal(firstResult.code, 0, firstResult.output); assert.equal(firstResult.candidateMutated, false); assert.equal(await readFile(join(candidate, 'candidate.txt'), 'utf8'), original)
  const firstEvidence = createEvidenceBundle({ plan: firstPlan, result: firstResult, signer, now: new Date('2026-08-18T12:00:00.000Z') }); assert.equal(firstEvidence.status, 'PASS'); assert.equal(validateEvidencePass(firstEvidence), true); assert.equal(firstEvidence.verifier.kind, 'INDEPENDENT_VERIFIER'); assert.equal(firstEvidence.environment.candidateMount, 'READ_ONLY')
  const secondPlan = await provisionVerificationSandbox({ candidateRoot: candidate, image, adapter, config: { checks: ['sha256'] } }); const secondResult = await executeVerificationSandbox(secondPlan); const secondEvidence = createEvidenceBundle({ plan: secondPlan, result: secondResult, signer, now: new Date('2026-08-18T12:00:00.000Z') }); assert.equal(secondEvidence.candidateDigest, firstEvidence.candidateDigest); assert.equal(secondEvidence.configDigest, firstEvidence.configDigest); assert.equal(secondEvidence.result.outputDigest, firstEvidence.result.outputDigest)
  const mutationAdapter = { ...adapter, verifierId: 'mutation-attempt', command: () => ['/bin/sh', '-c', 'echo denied >> candidate.txt'] }; const mutationPlan = await provisionVerificationSandbox({ candidateRoot: candidate, image, adapter: mutationAdapter }); const mutationResult = await executeVerificationSandbox(mutationPlan); assert.notEqual(mutationResult.code, 0); const failedEvidence = createEvidenceBundle({ plan: mutationPlan, result: mutationResult, signer }); assert.equal(failedEvidence.status, 'FAIL'); assert.throws(() => validateEvidencePass({ ...firstEvidence, result: { ...firstEvidence.result, outputDigest: null } }))
  const adapters = baselineVerifierAdapters(); assert.deepEqual(adapters.map((item) => item.category), verifierCategories); for (const adapterDefinition of adapters) { const plan = await provisionVerificationSandbox({ candidateRoot: candidate, image, adapter: adapterDefinition }); const result = await executeVerificationSandbox(plan); const evidence = createEvidenceBundle({ plan, result, signer }); assert.equal(result.code, 0, `${adapterDefinition.category}: ${result.output}`); assert.equal(evidence.verifier.category, adapterDefinition.category); assert.equal(evidence.verifier.tool.name, 'busybox'); assert.equal(validateEvidencePass(evidence), true) }; assert.throws(() => createVerifierAdapter({ category: 'BUILD', verifierId: 'unsafe', version: '1', tool: { name: 'x', version: '1' }, command: 'echo untrusted' }))
  console.log('Stage 6 independent fresh-verifier, read-only candidate, reproducible provenance, signed evidence-bundle, and pinned build/test/static/security/SBOM adapter verification passed.')
} finally { await rm(root, { recursive: true, force: true }) }
